site_name: lab.delthia.com
repo_url: https://github.com/delthia/docs
repo_name: delthia/docs

copyright: CC-BY 2023

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar al modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: yellow
      toggle:
        icon: material/toggle-switch-outline
        name: Cambiar al modo claro
  features:
    - content.code.annotate
    - navigation.footer
  icon:
    # repo: fontawesome/brands/git-alt
    repo: fontawesome/brands/github
    logo: material/flask

extra:
  social:
    - icon: material/github
      link: https://github.com/delthia
    - icon: material/email
      link: mailto:iago@delthia.com
    - icon: material/git
      link: https://codeberg.org/iago


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
